version: "3.9"
services:
  # PostgreSQL database
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: course4u
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cfu

  # Production backend service (Spring Boot)
  server-prod:
    build:
      context: ./server  # Path to backend project with Dockerfile
      dockerfile: Dockerfile
    container_name: "server-prod"
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    environment:
      - spring.web.resources.static-locations=file:/app/uploads
      - course4u.upload.thumbnail-directory=./uploads/api/thumbnail
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/course4u
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres
    networks:
      - cfu

  # Production frontend service (Vue.js + Nginx)
  client-prod:
    build:
      context: ./client  # Path to frontend project with Dockerfile
      dockerfile: Dockerfile
    container_name: "client-prod"
    restart: always
    ports:
      - "3000:80"
    networks:
      - cfu
    depends_on:
      - "server-prod"

networks:
  cfu:
    external: true
    name: cfu

volumes:
  postgres_data:
